markdown: kramdown
permalink: /:categories/:title.html
kramdown:
    use_coderay: true

default_layouts:
    documentation/.*: documentation
    changelog/.*: changelog
    index.md: index
    package_directory.md: package_directory
    pkg/.*: package_directory
    types/.*: package_directory
    sets/.*: package_directory
    osdeps/.*: package_directory
    tasks/.*: package_directory
    search_results.html: search_results
    ".*": default
