markdown: kramdown
permalink: /:categories/:title.html
kramdown:
    use_coderay: true

default_layouts:
    documentation/.*: documentation
    changelog/.*: changelog
    index.html: index
    package_directory/.*: package_directory
    search_results.html: search_results
    ".*": default
